use crate::pool::pool;
use larust_core::{axum, AppError};
use sqlx::query::QueryAs;
use sqlx::sqlite::{Sqlite, SqliteArguments};
use sqlx::SqlitePool;
use std::marker::PhantomData;

/// A dynamically-typed bind value — `where_eq` accepts any of these via
/// `Into<BindValue>` so the builder can accumulate heterogeneous
/// conditions (`where_eq(Post::TITLE, "x").where_eq(Post::ID, 1)`) in one
/// `Vec` before binding them to the query at execution time.
pub enum BindValue {
    Text(String),
    Int(i64),
    Bool(bool),
}

impl From<String> for BindValue {
    fn from(v: String) -> Self {
        BindValue::Text(v)
    }
}

impl From<&str> for BindValue {
    fn from(v: &str) -> Self {
        BindValue::Text(v.to_string())
    }
}

impl From<i64> for BindValue {
    fn from(v: i64) -> Self {
        BindValue::Int(v)
    }
}

impl From<bool> for BindValue {
    fn from(v: bool) -> Self {
        BindValue::Bool(v)
    }
}

/// One accumulated `WHERE` condition. Private — `where_eq`/`where_in` are
/// the only public ways to build one, so callers never construct this
/// directly.
enum Condition {
    Eq(&'static str, BindValue),
    In(&'static str, Vec<BindValue>),
}

/// Laravel-shaped query builder (`Post::query().where_eq(...).latest(...)`)
/// over `sqlx`. Column names passed in (`Post::TITLE`) are `&'static str`
/// constants generated by `#[derive(Model)]`, never user input, so they're
/// interpolated directly into the SQL string; bound *values* always go
/// through placeholders — never string-formatted into the query.
pub struct QueryBuilder<T> {
    table: &'static str,
    wheres: Vec<Condition>,
    order_by: Option<(&'static str, bool)>,
    limit: Option<i64>,
    _marker: PhantomData<fn() -> T>,
}

impl<T> QueryBuilder<T>
where
    T: for<'r> sqlx::FromRow<'r, sqlx::sqlite::SqliteRow> + Send + Unpin,
{
    pub fn new(table: &'static str) -> Self {
        Self {
            table,
            wheres: Vec::new(),
            order_by: None,
            limit: None,
            _marker: PhantomData,
        }
    }

    #[must_use]
    pub fn where_eq(mut self, column: &'static str, value: impl Into<BindValue>) -> Self {
        self.wheres.push(Condition::Eq(column, value.into()));
        self
    }

    /// `WHERE column IN (values...)` (Laravel's `->whereIn(...)`) — used by
    /// relationship batch loaders (`load_*`, see `larust-macros`'
    /// `relations.rs`) to fetch every related row for a whole batch of
    /// already-loaded rows in one query instead of one query per row.
    /// `values` empty is a real case (batch-loading relations for an empty
    /// input slice), not just a hypothetical — `build_sql` renders that as
    /// a condition that matches nothing (`1=0`), since `"col" IN ()` is
    /// invalid SQL in SQLite (a syntax error, not an empty-result query).
    #[must_use]
    pub fn where_in<V: Into<BindValue>>(mut self, column: &'static str, values: Vec<V>) -> Self {
        self.wheres.push(Condition::In(
            column,
            values.into_iter().map(Into::into).collect(),
        ));
        self
    }

    /// Orders by `column` descending (Laravel's `->latest($column)`).
    #[must_use]
    pub fn latest(mut self, column: &'static str) -> Self {
        self.order_by = Some((column, true));
        self
    }

    /// A stand-in for Laravel's `->paginate($perPage)` — limits to
    /// `per_page` rows. Page-number/metadata support (current page, total
    /// count, links) is a later addition; for now this is equivalent to
    /// `.limit(per_page).get()`.
    pub async fn paginate(mut self, per_page: i64) -> Result<Vec<T>, AppError> {
        if per_page <= 0 {
            return Err(AppError::Http {
                status: axum::http::StatusCode::UNPROCESSABLE_ENTITY,
                message: "pagination size must be greater than zero".to_string(),
            });
        }
        self.limit = Some(per_page);
        self.get().await
    }

    pub async fn get(self) -> Result<Vec<T>, AppError> {
        self.get_on(pool()?).await
    }

    /// Executes this query against an explicit pool. This is the preferred
    /// building block for applications moving away from process-wide ORM
    /// state, while `get()` remains compatible with existing models.
    pub async fn get_on(self, database: &SqlitePool) -> Result<Vec<T>, AppError> {
        let sql = self.build_sql(None);
        let query = bind_all(sqlx::query_as::<_, T>(&sql), &self.wheres);
        query
            .fetch_all(database)
            .await
            .map_err(|e| AppError::Internal(Box::new(e)))
    }

    pub async fn first(self) -> Result<Option<T>, AppError> {
        self.first_on(pool()?).await
    }

    pub async fn first_on(self, database: &SqlitePool) -> Result<Option<T>, AppError> {
        let sql = self.build_sql(Some(1));
        let query = bind_all(sqlx::query_as::<_, T>(&sql), &self.wheres);
        query
            .fetch_optional(database)
            .await
            .map_err(|e| AppError::Internal(Box::new(e)))
    }

    pub async fn count(self) -> Result<i64, AppError> {
        self.count_on(pool()?).await
    }

    pub async fn count_on(self, database: &SqlitePool) -> Result<i64, AppError> {
        let sql = self.build_count_sql();
        let query = bind_all(sqlx::query_as::<_, (i64,)>(&sql), &self.wheres);
        query
            .fetch_one(database)
            .await
            .map(|(count,)| count)
            .map_err(|e| AppError::Internal(Box::new(e)))
    }

    pub async fn exists(self) -> Result<bool, AppError> {
        Ok(self.first().await?.is_some())
    }

    fn build_sql(&self, first_limit: Option<i64>) -> String {
        // Every identifier here is quoted (`"..."`) — `self.table` and each
        // `column` are always `&'static str` constants generated by
        // `#[derive(Model)]` from a table/field name, never runtime data,
        // so quoting is about not colliding with a SQL reserved keyword
        // (a field named `order`, say), not about injection.
        let mut sql = format!("SELECT * FROM \"{}\"", self.table);

        if !self.wheres.is_empty() {
            let clauses: Vec<String> = self.wheres.iter().map(render_condition).collect();
            sql.push_str(" WHERE ");
            sql.push_str(&clauses.join(" AND "));
        }

        if let Some((column, descending)) = self.order_by {
            let direction = if descending { "DESC" } else { "ASC" };
            sql.push_str(&format!(" ORDER BY \"{column}\" {direction}"));
        }

        if let Some(limit) = first_limit.or(self.limit) {
            sql.push_str(&format!(" LIMIT {limit}"));
        }

        sql
    }

    fn build_count_sql(&self) -> String {
        let mut sql = format!("SELECT COUNT(*) FROM \"{}\"", self.table);
        if !self.wheres.is_empty() {
            let clauses: Vec<String> = self.wheres.iter().map(render_condition).collect();
            sql.push_str(" WHERE ");
            sql.push_str(&clauses.join(" AND "));
        }
        sql
    }
}

/// Renders one condition's SQL fragment (no values — those are bound
/// separately by `bind_all`, in the same left-to-right order this
/// function's placeholders appear in).
fn render_condition(condition: &Condition) -> String {
    match condition {
        Condition::Eq(column, _) => format!("\"{column}\" = ?"),
        // Empty IN-list: "col" IN () is a SQLite syntax error, not an
        // empty-result query — 1=0 is the standard always-false
        // substitute, so `where_in(col, vec![])` correctly yields zero
        // rows instead of failing the whole query.
        Condition::In(_, values) if values.is_empty() => "1=0".to_string(),
        Condition::In(column, values) => {
            let placeholders = values.iter().map(|_| "?").collect::<Vec<_>>().join(", ");
            format!("\"{column}\" IN ({placeholders})")
        }
    }
}

fn bind_all<'q, T>(
    mut query: QueryAs<'q, Sqlite, T, SqliteArguments<'q>>,
    conditions: &'q [Condition],
) -> QueryAs<'q, Sqlite, T, SqliteArguments<'q>> {
    for condition in conditions {
        let values: &[BindValue] = match condition {
            Condition::Eq(_, value) => std::slice::from_ref(value),
            Condition::In(_, values) => values,
        };
        for value in values {
            query = match value {
                BindValue::Text(s) => query.bind(s),
                BindValue::Int(i) => query.bind(i),
                BindValue::Bool(b) => query.bind(b),
            };
        }
    }
    query
}

#[cfg(test)]
mod tests {
    use super::*;

    #[derive(sqlx::FromRow)]
    struct Dummy {
        #[allow(dead_code)]
        id: i64,
    }

    #[test]
    fn quotes_table_and_column_identifiers_so_reserved_keywords_are_safe() {
        let qb: QueryBuilder<Dummy> = QueryBuilder::new("order")
            .where_eq("group", 1i64)
            .latest("select");

        assert_eq!(
            qb.build_sql(None),
            "SELECT * FROM \"order\" WHERE \"group\" = ? ORDER BY \"select\" DESC"
        );
    }

    #[test]
    fn build_sql_with_no_conditions() {
        let qb: QueryBuilder<Dummy> = QueryBuilder::new("posts");
        assert_eq!(qb.build_sql(None), "SELECT * FROM \"posts\"");
        assert_eq!(qb.build_sql(Some(1)), "SELECT * FROM \"posts\" LIMIT 1");
    }

    #[test]
    fn where_in_renders_one_placeholder_per_value() {
        let qb: QueryBuilder<Dummy> = QueryBuilder::new("posts").where_in("id", vec![1i64, 2, 3]);
        assert_eq!(
            qb.build_sql(None),
            "SELECT * FROM \"posts\" WHERE \"id\" IN (?, ?, ?)"
        );
    }

    #[test]
    fn where_in_with_a_single_value() {
        let qb: QueryBuilder<Dummy> = QueryBuilder::new("posts").where_in("id", vec![1i64]);
        assert_eq!(
            qb.build_sql(None),
            "SELECT * FROM \"posts\" WHERE \"id\" IN (?)"
        );
    }

    #[test]
    fn where_in_with_an_empty_list_renders_an_always_false_condition() {
        // "id" IN () is a SQLite syntax error, not an empty-result query —
        // this must render as something SQLite accepts and that matches
        // zero rows.
        let qb: QueryBuilder<Dummy> = QueryBuilder::new("posts").where_in("id", Vec::<i64>::new());
        assert_eq!(qb.build_sql(None), "SELECT * FROM \"posts\" WHERE 1=0");
    }

    #[test]
    fn where_in_quotes_the_column_identifier() {
        let qb: QueryBuilder<Dummy> = QueryBuilder::new("posts").where_in("order", vec![1i64]);
        assert_eq!(
            qb.build_sql(None),
            "SELECT * FROM \"posts\" WHERE \"order\" IN (?)"
        );
    }

    #[test]
    fn where_eq_and_where_in_combine_with_and() {
        let qb: QueryBuilder<Dummy> = QueryBuilder::new("posts")
            .where_eq("title", "hi")
            .where_in("id", vec![1i64, 2]);
        assert_eq!(
            qb.build_sql(None),
            "SELECT * FROM \"posts\" WHERE \"title\" = ? AND \"id\" IN (?, ?)"
        );
    }
}
