[package]
name = "larust-mail"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
larust-core = { workspace = true }
larust-queue = { workspace = true }
tracing = { workspace = true }
lettre = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
larust-orm = { workspace = true }
tempfile = { workspace = true }
sqlx = { workspace = true }
serde_json = { workspace = true }
