[package]
name = "larust-support"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ammonia = { workspace = true }
axum = { workspace = true }
chrono = { workspace = true }
larust-auth = { workspace = true }
larust-cache = { workspace = true }
larust-core = { workspace = true }
larust-events = { workspace = true }
larust-http = { workspace = true }
larust-live = { workspace = true }
larust-macros = { workspace = true }
larust-mail = { workspace = true }
larust-notifications = { workspace = true }
larust-orm = { workspace = true }
larust-permissions = { workspace = true }
larust-queue = { workspace = true }
larust-sanctum = { workspace = true }
larust-scheduler = { workspace = true }
larust-sitemap = { workspace = true }
larust-storage = { workspace = true }
larust-validation = { workspace = true }
larust-view = { workspace = true }
regex = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
